name = 'Bare Bones'
license = 'MIT'
licenselink = 'https://codeberg.org/flagranterror/hugo-bare-bones/LICENSE'
description = 'Very simple theme based on Better MF Website'

# The home page of the theme, where the source can be found
homepage = 'https://codeberg.org/flagranterror/hugo-bare-bones'

# # If you have a running demo of the theme
# demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['blog']
features = ['minimal', 'fast']

# If the theme has multiple authors
#authors = [
#  {name = 'Name of author', homepage = 'Website of author'},
#  {name = 'Name of author', homepage = 'Website of author'}
#]

# If the theme has a single author
[author]
  name = 'Doug McNish'
  homepage = 'https://no.bickering.online'

